/*******************************************************************************
 * @file descriptors.c
 * @brief USB descriptors.
 *******************************************************************************/

//=============================================================================
// src/descriptors.c: generated by Hardware Configurator
//
// This file is only generated if it does not exist. Modifications in this file
// will persist even if Configurator generates code. To refresh this file,
// you must first delete it and then regenerate code.
//=============================================================================
//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <si_toolchain.h>
#include <endian.h>
#include <stdlib.h>
#include <string.h>
#include <efm8_usb.h>
#include "descriptors.h"

#ifdef __cplusplus
extern "C" {
#endif

SI_SEGMENT_VARIABLE(deviceDesc[],
		const USB_DeviceDescriptor_TypeDef,
		SI_SEG_CODE) =
{
	USB_DEVICE_DESCSIZE,             // bLength
	USB_DEVICE_DESCRIPTOR,// bLength
	htole16(0x0200),// bcdUSB
	0,// bDeviceClass
	0,// bDeviceSubClass
	0,// bDeviceProtocol
	64,// bMaxPacketSize
	USB_VENDOR_ID,// idVendor
	USB_PRODUCT_ID,// idProduct
	htole16(0x0100),// bcdDevice
	1,// iManufacturer
	2,// iProduct
	3,// iSerialNumber
	1,// bNumConfigurations
};

SI_SEGMENT_VARIABLE(configDesc[],
		const uint8_t,
		SI_SEG_CODE) =
{
	USB_CONFIG_DESCSIZE,             // bLength
	USB_CONFIG_DESCRIPTOR,// bLength
	0x1B,// wTotalLength(LSB)
	0x00,// wTotalLength(MSB)
	2,// bNumInterfaces
	1,// bConfigurationValue
	4,// iConfiguration

	CONFIG_DESC_BM_RESERVED_D7 |// bmAttrib: Self powered
	CONFIG_DESC_BM_SELFPOWERED,

	CONFIG_DESC_MAXPOWER_mA(100),// bMaxPower: 100 mA

	//Interface 0 Descriptor
	USB_INTERFACE_DESCSIZE,// bLength
	USB_INTERFACE_DESCRIPTOR,// bDescriptorType
	0,// bInterfaceNumber
	0,// bAlternateSetting
	0,// bNumEndpoints
	255,// bInterfaceClass: Vendor Specific
	255,// bInterfaceSubClass
	255,// bInterfaceProtocol
	5,// iInterface

	//Interface 1 Descriptor
	USB_INTERFACE_DESCSIZE,// bLength
	USB_INTERFACE_DESCRIPTOR,// bDescriptorType
	1,// bInterfaceNumber
	0,// bAlternateSetting
	0,// bNumEndpoints
	2,// bInterfaceClass: Communications and CDC Control
	0,// bInterfaceSubClass
	0,// bInterfaceProtocol
	6,// iInterface
};

#define LANG_STRING   htole16( SLAB_USB_LANGUAGE )
#define MFR_STRING                                'S','i','l','i','c','o','n',' ','L','a','b','s','\0'
#define MFR_SIZE                                  13
#define PROD_STRING                               'G','e','n','e','r','i','c',' ','U','S','B',' ','D','e','v','i','c','e','\0'
#define PROD_SIZE                                 19
#define SER_STRING                                '0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','\0'
#define SER_SIZE                                  17
#define CFG_STRING                                'C','o','n','f','i','g',' ','#','1','\0'
#define CFG_SIZE                                  10
#define INT0_STRING                               'C','u','s','t','o','m',' ','I','n','t','e','r','f','a','c','e','\0'
#define INT0_SIZE                                 17
#define INT1_STRING                               'C','u','s','t','o','m',' ','I','n','t','e','r','f','a','c','e','\0'
#define INT1_SIZE                                 17

LANGID_STATIC_CONST_STRING_DESC( langDesc[], LANG_STRING );
UTF16LE_PACKED_STATIC_CONST_STRING_DESC( mfrDesc[], MFR_STRING, MFR_SIZE);
UTF16LE_PACKED_STATIC_CONST_STRING_DESC( prodDesc[], PROD_STRING, PROD_SIZE);
UTF16LE_PACKED_STATIC_CONST_STRING_DESC( serDesc[], SER_STRING, SER_SIZE);
UTF16LE_PACKED_STATIC_CONST_STRING_DESC( cfgDesc[], CFG_STRING, CFG_SIZE);
UTF16LE_PACKED_STATIC_CONST_STRING_DESC( int0Desc[], INT0_STRING, INT0_SIZE);
UTF16LE_PACKED_STATIC_CONST_STRING_DESC( int1Desc[], INT1_STRING, INT1_SIZE);

//-----------------------------------------------------------------------------
SI_SEGMENT_VARIABLE_SEGMENT_POINTER(myUsbStringTable_USEnglish[]
		, static const USB_StringDescriptor_TypeDef,
		SI_SEG_GENERIC,
		const SI_SEG_CODE) =
{
	(SI_VARIABLE_SEGMENT_POINTER(, uint8_t, SI_SEG_CODE))langDesc,
	mfrDesc,
	prodDesc,
	serDesc,
	cfgDesc,
	int0Desc,
	int1Desc,

};

//-----------------------------------------------------------------------------
SI_SEGMENT_VARIABLE(initstruct,
		const USBD_Init_TypeDef,
		SI_SEG_CODE) =
{
	(SI_VARIABLE_SEGMENT_POINTER(, USB_DeviceDescriptor_TypeDef, SI_SEG_GENERIC))deviceDesc, // deviceDescriptor
	(SI_VARIABLE_SEGMENT_POINTER(, USB_ConfigurationDescriptor_TypeDef, SI_SEG_GENERIC))configDesc,// configDescriptor
	(SI_VARIABLE_SEGMENT_POINTER(, USB_StringTable_TypeDef, SI_SEG_GENERIC))myUsbStringTable_USEnglish,// stringDescriptors
	sizeof(myUsbStringTable_USEnglish) / sizeof(myUsbStringTable_USEnglish[0])// numberOfStrings
};

#ifdef __cplusplus
}
#endif

